# -*- Makefile -*-

# Set the name of the project here
PROJECT_NAME := klee
PROJ_VERSION := 0.01

# Set this variable to the top of the LLVM source tree.
LLVM_SRC_ROOT = /home/bo/KleeWorkspace/llvm-2.9

# Set this variable to the top level directory where LLVM was built
# (this is *not* the same as OBJ_ROOT as defined in LLVM's Makefile.config).
LLVM_OBJ_ROOT = /home/bo/KleeWorkspace/llvm-2.9

LLVM_VERSION_MAJOR = 2
LLVM_VERSION_MINOR = 9

# Set this to the build mode used to build LLVM (not necessarily the same
# as the build mode used for KLEE)
LLVM_BUILD_MODE = Release+Asserts

# Set the directory root of this project's source files
PROJ_SRC_ROOT := $(subst //,/,/home/bo/workspace/klee-g/UNIT-KLEE)

# Set the root directory of this project's object files
PROJ_OBJ_ROOT := $(subst //,/,/home/bo/workspace/klee-g/UNIT-KLEE)

# Set the root directory of this project's install prefix
PROJ_INSTALL_ROOT := /usr/local

STP_ROOT := /home/bo/KleeWorkspace/stp-stp-614848b/build

STP_NEEDS_BOOST := 0

ifeq ($(STP_NEEDS_BOOST),1)
 UPSTREAM_STP_LINK_FLAGS = -lboost_system -lboost_program_options
endif

ENABLE_METASMT := 0
METASMT_ROOT := 

ENABLE_POSIX_RUNTIME := 0
ENABLE_STPLOG := @ENABLE_STPLOG@
ENABLE_UCLIBC := 0

KLEE_UCLIBC_BCA := 

HAVE_SELINUX := 0

RUNTIME_ENABLE_OPTIMIZED := 1
RUNTIME_DISABLE_ASSERTIONS := 0
RUNTIME_DEBUG_SYMBOLS := 
RUNTIME_ENABLE_COVERAGE :=
RUNTIME_ENABLE_PROFILING :=

# Compilers used to build runtime library and run tests
KLEE_BITCODE_C_COMPILER := /home/bo/Tools/llvm-gcc4.2-2.9-x86_64-linux/bin/llvm-gcc
KLEE_BITCODE_CXX_COMPILER := /home/bo/Tools/llvm-gcc4.2-2.9-x86_64-linux/bin/llvm-g++

# A list of "features" which tests can check for in XFAIL:
TEST_FEATURE_LIST :=

ifeq ($(HAVE_SELINUX_SELINUX_H),1)
  TEST_FEATURE_LIST += have-selinux
else
  TEST_FEATURE_LIST += no-selinux
endif

# disable unwind test
TEST_FEATURE_LIST += no-unwind

CFLAGS := -g -O2 -Wall -g
CXXFLAGS := -g -O2 -g -Wall
LDFLAGS :=  -g

REQUIRES_RTTI := 0
RUNTEST := @RUNTEST@
TCLSH := @TCLSH@
